### ISSUE TITLE
Somes bugs

### ISSUE THREAD

**Issue by JiKay12** [Freebi85/Explorico_easy#6]
Hey ! After play ~30 hours on the pack, i have somes litlle problems

Craft Conflicts : 

Terra tools (spade, sword and hoe)  all have the same craft, 2 terrasteel and 1 living wood stick with a sword pattern 

- Somes seeds are not allow in the botany pot :

lumium, signalum and enderium seed, Blizz, blitz and Basalt seed from Thermal (maybe fix in the last version, i was on 1.2)
HOP seed for Immersive
energized, blazing, niotic, spirited and uraninite seeds from Powah

**Comment by Freebi85** [comment]
Thank you will look into this :)

Cheers 🍻
