### ISSUE TITLE
Fix Suggested - "Infinite" Potion effects due to Magic Siphon (Apotheosis)

### ISSUE THREAD

**Issue by Danekjovax** [Freebi85/Explorico_easy#7]
https://github.com/Darkhax-Minecraft/Corail-Tombstone/issues/25
https://github.com/Shadows-of-Fire/Apotheosis/issues/268

Apparently, Corail default timer for siphon'd effects from certain mobs is 1440 seconds.  It is found here:
config - tombstone-common.toml, line159:
max_duration_magic_siphon = 60 (in minutes)

I suggest changing it to something more realistic, like 5-8, to match regular potions.

Thanks!

**Comment by Freebi85** [comment]
Thank you vey much for researching, will look into this 👀

**Comment by Danekjovax** [comment]
Updated OP.
